"""Initial migration

Revision ID: 1191d11f60ca
Revises: 
Create Date: 2022-07-02 17:36:09.660036

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1191d11f60ca"
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()


def upgrade_primary() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parking_slots",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="available", nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_parking_slots_uuid"), "parking_slots", ["uuid"], unique=True
    )
    # ### end Alembic commands ###


def downgrade_primary() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parking_slots_uuid"), table_name="parking_slots")
    op.drop_table("parking_slots")
    # ### end Alembic commands ###


def upgrade_replica() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parking_slots",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="available", nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_parking_slots_uuid"), "parking_slots", ["uuid"], unique=True
    )
    # ### end Alembic commands ###


def downgrade_replica() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parking_slots_uuid"), table_name="parking_slots")
    op.drop_table("parking_slots")
    # ### end Alembic commands ###
