from starlette.config import Config

config = Config()

EVENT_STORE_DATABASE_URL = config("EVENT_STORE_DATABASE_URL")
PROJECTOR_DATABASE_URL = config("PROJECTOR_DATABASE_URL")
RABBITMQ_BROKER_URL = config("RABBITMQ_BROKER_URL")
SQLALCHEMY_URL = config("SQLALCHEMY_URL")
