"""Initial migration

Revision ID: 04d2920ac9fd
Revises: 
Create Date: 2022-05-19 20:27:46.304740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d2920ac9fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_requests',
    sa.Column('booking_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('booking_id'),
    schema='billing_schema'
    )
    op.create_index(op.f('ix_billing_schema_billing_requests_booking_id'), 'billing_requests', ['booking_id'], unique=True, schema='billing_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_schema_billing_requests_booking_id'), table_name='billing_requests', schema='billing_schema')
    op.drop_table('billing_requests', schema='billing_schema')
    # ### end Alembic commands ###
