"""Update PaymentReconciliation.billing_request lazy dynamic

Revision ID: 1cc554451896
Revises: 780e8c4bae27
Create Date: 2022-05-22 08:30:20.422569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc554451896'
down_revision = '780e8c4bae27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payment_reconciliations_billing_request_id_fkey', 'payment_reconciliations', type_='foreignkey')
    op.create_foreign_key(None, 'payment_reconciliations', 'billing_requests', ['billing_request_id'], ['id'], source_schema='billing_schema', referent_schema='billing_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_reconciliations', schema='billing_schema', type_='foreignkey')
    op.create_foreign_key('payment_reconciliations_billing_request_id_fkey', 'payment_reconciliations', 'billing_requests', ['billing_request_id'], ['id'])
    # ### end Alembic commands ###
