"""Initial migration

Revision ID: 207207faeb87
Revises: 
Create Date: 2022-05-21 19:12:35.284852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207207faeb87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reference_no', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_no'),
    schema='billing_schema'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_requests', schema='billing_schema')
    # ### end Alembic commands ###
