"""Add total field to BillingRequest model

Revision ID: 3a6f9142051f
Revises: 04d2920ac9fd
Create Date: 2022-05-20 06:55:19.927253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6f9142051f'
down_revision = '04d2920ac9fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_requests', sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_requests', 'total')
    # ### end Alembic commands ###
