"""Add backref to PaymentReconciliation.billing_request

Revision ID: 780e8c4bae27
Revises: bcb6a47bfbbe
Create Date: 2022-05-22 08:21:55.642530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780e8c4bae27'
down_revision = 'bcb6a47bfbbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payment_reconciliations_billing_request_id_fkey', 'payment_reconciliations', type_='foreignkey')
    op.create_foreign_key(None, 'payment_reconciliations', 'billing_requests', ['billing_request_id'], ['id'], source_schema='billing_schema', referent_schema='billing_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_reconciliations', schema='billing_schema', type_='foreignkey')
    op.create_foreign_key('payment_reconciliations_billing_request_id_fkey', 'payment_reconciliations', 'billing_requests', ['billing_request_id'], ['id'])
    # ### end Alembic commands ###
