"""Create PaymentReconciliation model

Revision ID: bcb6a47bfbbe
Revises: 207207faeb87
Create Date: 2022-05-22 07:26:18.078524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcb6a47bfbbe'
down_revision = '207207faeb87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_reconciliations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('billing_request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['billing_request_id'], ['billing_schema.billing_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='billing_schema'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_reconciliations', schema='billing_schema')
    # ### end Alembic commands ###
