"""Update BookingRequest.approved type from String to Boolean

Revision ID: 91640caa1337
Revises: f80a719aba3d
Create Date: 2022-05-18 19:23:44.525848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91640caa1337'
down_revision = 'f80a719aba3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking_request', 'approved',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=False,
               postgresql_using='approved::boolean'
            )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking_request', 'approved',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
