"""Initial Migration

Revision ID: cbe924e50027
Revises: 
Create Date: 2022-05-09 17:49:23.387615

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'cbe924e50027'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookingrequest',
    sa.Column('booking_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('booking_id'),
    schema='manager_schema'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookingrequest', schema='manager_schema')
    # ### end Alembic commands ###
