"""Initial migration

Revision ID: 74f91803e544
Revises: 
Create Date: 2022-06-11 19:49:05.600874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f91803e544'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reference_no', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_requests')
    # ### end Alembic commands ###
