"""Removal of description column

Revision ID: caeb28082687
Revises: d6bb61f1e755
Create Date: 2022-05-23 19:59:44.995294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caeb28082687'
down_revision = 'd6bb61f1e755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'description', schema='booking_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False), schema='booking_schema')
    # ### end Alembic commands ###