"""Add status field

Revision ID: 2efeb1766d65
Revises: 3a414c21545c
Create Date: 2022-05-23 19:30:31.238388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2efeb1766d65'
down_revision = '3a414c21545c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking_slots', sa.Column('status', sa.String(), server_default='pending', nullable=False), schema='parking_schema')
    op.create_index(op.f('ix_parking_schema_parking_slots_uuid'), 'parking_slots', ['uuid'], unique=True, schema='parking_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parking_schema_parking_slots_uuid'), table_name='parking_slots', schema='parking_schema')
    op.drop_column('parking_slots', 'status', schema='parking_schema')
    # ### end Alembic commands ###
