"""Rename Booking.parking_slot_uuid to Booking.parking_slot_ref_no

Revision ID: 29af7026cb10
Revises: caeb28082687
Create Date: 2022-05-28 19:42:20.938039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29af7026cb10'
down_revision = 'caeb28082687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'parking_slot_uuid', new_column_name='parking_slot_ref_no', schema='booking_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        op.alter_column('bookings', 'parking_slot_ref_no', new_column_name='parking_slot_uuid', schema='booking_schema')
    # ### end Alembic commands ###