"""Initial migration

Revision ID: 88a01597d38a
Revises: 
Create Date: 2022-05-14 15:47:04.404716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a01597d38a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    schema='booking_schema'
    )
    op.create_index(op.f('ix_booking_schema_booking_uuid'), 'booking', ['uuid'], unique=True, schema='booking_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_schema_booking_uuid'), table_name='booking', schema='booking_schema')
    op.drop_table('booking', schema='booking_schema')
    # ### end Alembic commands ###