"""Alter parking_space_no to parking_slot_uuid

Revision ID: d6bb61f1e755
Revises: a2f83ffe751f
Create Date: 2022-05-23 19:58:24.303388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6bb61f1e755'
down_revision = 'a2f83ffe751f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('parking_slot_uuid', sa.String(), nullable=True), schema='booking_schema')
    op.drop_column('bookings', 'parking_space_uuid', schema='booking_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('parking_space_uuid', sa.VARCHAR(), autoincrement=False, nullable=True), schema='booking_schema')
    op.drop_column('bookings', 'parking_slot_uuid', schema='booking_schema')
    # ### end Alembic commands ###