"""Change table name from booking to bookings

Revision ID: f96307a1d404
Revises: 88a01597d38a
Create Date: 2022-05-21 17:37:44.830897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96307a1d404'
down_revision = '88a01597d38a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    schema='booking_schema'
    )
    op.create_index(op.f('ix_booking_schema_bookings_uuid'), 'bookings', ['uuid'], unique=True, schema='booking_schema')
    op.drop_index('ix_booking_schema_booking_uuid', table_name='booking')
    op.drop_table('booking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uuid', name='booking_pkey')
    )
    op.create_index('ix_booking_schema_booking_uuid', 'booking', ['uuid'], unique=False)
    op.drop_index(op.f('ix_booking_schema_bookings_uuid'), table_name='bookings', schema='booking_schema')
    op.drop_table('bookings', schema='booking_schema')
    # ### end Alembic commands ###